<?php
declare(strict_types=1);

// HubspotSettings SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

HubspotSettingsUtility::setRegistrar(function (HubspotSettingsUtility $u): void {
    $u->clean = [HubspotSettingsClean::class, 'call'];
    $u->done = [HubspotSettingsDone::class, 'call'];
    $u->make_error = [HubspotSettingsMakeError::class, 'call'];
    $u->feature_add = [HubspotSettingsFeatureAdd::class, 'call'];
    $u->feature_hook = [HubspotSettingsFeatureHook::class, 'call'];
    $u->feature_init = [HubspotSettingsFeatureInit::class, 'call'];
    $u->fetcher = [HubspotSettingsFetcher::class, 'call'];
    $u->make_fetch_def = [HubspotSettingsMakeFetchDef::class, 'call'];
    $u->make_context = [HubspotSettingsMakeContext::class, 'call'];
    $u->make_options = [HubspotSettingsMakeOptions::class, 'call'];
    $u->make_request = [HubspotSettingsMakeRequest::class, 'call'];
    $u->make_response = [HubspotSettingsMakeResponse::class, 'call'];
    $u->make_result = [HubspotSettingsMakeResult::class, 'call'];
    $u->make_point = [HubspotSettingsMakePoint::class, 'call'];
    $u->make_spec = [HubspotSettingsMakeSpec::class, 'call'];
    $u->make_url = [HubspotSettingsMakeUrl::class, 'call'];
    $u->param = [HubspotSettingsParam::class, 'call'];
    $u->prepare_auth = [HubspotSettingsPrepareAuth::class, 'call'];
    $u->prepare_body = [HubspotSettingsPrepareBody::class, 'call'];
    $u->prepare_headers = [HubspotSettingsPrepareHeaders::class, 'call'];
    $u->prepare_method = [HubspotSettingsPrepareMethod::class, 'call'];
    $u->prepare_params = [HubspotSettingsPrepareParams::class, 'call'];
    $u->prepare_path = [HubspotSettingsPreparePath::class, 'call'];
    $u->prepare_query = [HubspotSettingsPrepareQuery::class, 'call'];
    $u->graphql_body = [HubspotSettingsGraphql::class, 'body'];
    $u->graphql_errors = [HubspotSettingsGraphql::class, 'errors'];
    $u->result_basic = [HubspotSettingsResultBasic::class, 'call'];
    $u->result_body = [HubspotSettingsResultBody::class, 'call'];
    $u->result_headers = [HubspotSettingsResultHeaders::class, 'call'];
    $u->transform_request = [HubspotSettingsTransformRequest::class, 'call'];
    $u->transform_response = [HubspotSettingsTransformResponse::class, 'call'];
});
